name: da_teamproject_env1
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.17.2=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aws-c-auth=0.9.1=h7ca4310_7
  - aws-c-cal=0.9.10=h346e085_1
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h3cb25bf_6
  - aws-c-http=0.10.7=hc5c8343_4
  - aws-c-io=0.23.3=ha76f1cc_3
  - aws-c-mqtt=0.13.3=h3a25ec9_10
  - aws-c-s3=0.10.1=hcb69869_2
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.2=h2ceb62e_4
  - aws-sdk-cpp=1.11.606=hd6e39bc_7
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.10.1=pyh707e725_0
  - cuda-version=12.9=h4f385c5_3
  - cyrus-sasl=2.1.28=hd9c7081_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - greenlet=3.2.4=py312h1289d80_1
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h2937f24_4_cuda
  - libarrow-acero=22.0.0=hb826db4_4_cuda
  - libarrow-compute=22.0.0=h58682fd_4_cuda
  - libarrow-dataset=22.0.0=hb826db4_4_cuda
  - libarrow-substrait=22.0.0=h9d9f3f8_4_cuda
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=2_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=he0feb66_14
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=2_h47877c9_openblas
  - liblightgbm=4.6.0=cuda129_h897a41e_6
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h31208bf_4_cuda
  - libpq=18.1=h5c52fec_2
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libthrift=0.22.0=h454ac66_1
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=3.1.2=cuda129_h54c741a_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightgbm=4.6.0=cuda129_py_6
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - nccl=2.28.9.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.3.5=py312h33ff503_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pip=25.3=pyh8b19718_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psycopg2=2.9.10=py312hf59bad3_4
  - psycopg2-binary=2.9.10=pyhd8ed1ab_1
  - py-xgboost=3.1.2=cuda129_pyha75543c_1
  - pyarrow=22.0.0=py312h7900ff3_0
  - pyarrow-core=22.0.0=py312hc62261d_0_cuda
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - s2n=1.6.0=h8399546_1
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.3=py312h7a1785b_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlalchemy=2.0.44=py312h4c3975b_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xgboost=3.1.2=cuda129_pyh5c66634_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=h3691f8a_4
prefix: /home/ga111o/miniforge3/envs/da_teamproject_env1
